### ISSUE TITLE
[Question] How to assign sub domain to different table?

### ISSUE THREAD

**Issue by krisnaw** [DigitalWheat/Multi-Domain-Laravel#1]
Hi there, 

Quick question. I'm curious how do you make route listen to 'domain' column on shops tables? Is that mean 1 user can have multiple shops with multiple subdomain?

Thanks, looking forward.

**Comment by maxkostinevich** [comment]
Hi,

Yes, each user can own several stores. 
For more information, please see:
1. routes/web.php (Line 49+)
2. app/Shop.php Model
3. app/Http/Middleware/CheckShopDomain.php which checks the subdomain
4. app/Http/helpers.php for helper functions

**Comment by krisnaw** [comment]
Hi @maxkostinevich, 
Thanks for the responses. 
The issue was I forgot to add wildcard on the DNS. But now is sorted. 1 user can have multiple subdomains.
