### ISSUE TITLE
Managing Domain instead of Sub Domain

### ISSUE THREAD

**Issue by rainbowhat** [DigitalWheat/Multi-Domain-Laravel#2]
Hi,

Could I use this method to manage multiple main domains? 
If possible, what about catch all *.*.com

**Comment by Qoraiche** [comment]
description says multi-domain/subdomain, so answer is yes.

**Comment by huzzi** [comment]
How would you map domain eg: mystore.com instead of shop.example.com?

**Comment by maxkostinevich** [comment]
You'll need to add an option for users to add a custom domain name to their stores and ask them to point the domain to your server by adding "A" record in the DNS settings.

I've created a short demo: https://github.com/laravel-101/multi-domain-laravel-app (the video is coming soon).
